export const REQUEST = '_REQUEST';
export const SUCCESS = '_SUCCESS';
export const FAILURE = '_FAILURE';

export const INCREASE_CART = 'INCREASE_CART';
export const DECREASE_CART = 'DECREASE_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const MAKE_ORDER = 'MAKE_ORDER';
export const PROCESS_CHECKOUT = 'PROCESS_CHECKOUT';

export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const LOAD_PRODUCT = 'LOAD_PRODUCT';
export const LOAD_REVIEWS = 'LOAD_REVIEWS';

export const SET_ACTIVE_CATEGORIES = 'SET_ACTIVE_CATEGORIES';

export const ROUTER_LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

export const ADD_REVIEW = 'ADD_REVIEW';




